# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'OneSignal', '~>1.13.3'
  # Pods for DemoApp



  target 'DemoAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'DemoApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DemoApp-tvOS

  target 'DemoApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


